
ARG BASE_IMAGE
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE:?err}:${BASE_IMAGE_TAG:?err} AS norlab-slurm-setup

ARG IS_TEAMCITY_RUN
ENV IS_TEAMCITY_RUN=${IS_TEAMCITY_RUN:-false}

ENV DN_PROJECT_SERVICE=project-slurm
ENV DN_PROJECT_SERVICE_DIR=/dockerized-norlab/project/${DN_PROJECT_SERVICE}


SHELL ["/usr/local/bin/bash-dn-buildtime", "-c"]
ARG DEBIAN_FRONTEND=noninteractive

RUN <<EOF
    echo "Pre-condition checks"
    {
        test $(whoami) == "root" &&  \
        test -n ${DN_PROJECT_USER:?'Env variable need to be set and non-empty.'} && \
        test -d /home/${DN_PROJECT_USER} && \
        test -n ${DN_PROJECT_UID:?'Env variable need to be set and non-empty.'} && \
        test -n ${DN_PROJECT_GID:?'Env variable need to be set and non-empty.'} && \
        test -n ${DN_PROJECT_PATH:?'Env variable need to be set and non-empty.'} && \
        test -n ${DN_PROJECT_SERVICE_DIR:?'Env variable need to be set and non-empty.'} && \
        test -n ${DN_PROJECT_GIT_NAME:?'Env variable need to be set and non-empty.'} && \
        test -n ${DN_PROJECT_GIT_DOMAIN:?'Env variable need to be set and non-empty.'} ;
    } || exit 1

EOF

WORKDIR /tmp/numba_cache
ENV NUMBA_CACHE_DIR=/tmp/numba_cache

WORKDIR ${DN_PROJECT_SERVICE_DIR}
COPY --chown="$(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER})" --from=context-dna-lib-container-tools project_entrypoints/${DN_PROJECT_SERVICE}/dn_entrypoint.slurm.bash ./
COPY --chown="$(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER})" .dockerized_norlab/configuration/project_entrypoints/project-slurm .

RUN <<EOF
    chmod 777 /tmp/numba_cache

    if [[ -f "/etc/matplotlibrc" ]]; then
        if grep -q 'backend : Agg' "/etc/matplotlibrc" 2>/dev/null; then
            echo "Configure Matplotlib to use a non-interactive backends for TeamCity run"
            echo "backend : Agg" >> /etc/matplotlibrc
        fi
    fi

    chmod +x ./dn_entrypoint.slurm.bash
EOF


# ====Execute slurm run============================================================================
FROM norlab-slurm-setup AS execute-slurm-run

USER ${DN_PROJECT_USER:?err}
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR ${DN_PROJECT_PATH:?'Required DN environment variable is empty or not set'}

RUN <<EOF
    test -x "${DN_PROJECT_SERVICE_DIR}/dn_entrypoint.slurm.bash" || exit 1

    n2st::print_msg "Check project files ownership..."
    incorrect_files=$(find ${DN_PROJECT_PATH} ! -user "${DN_PROJECT_UID}" -o ! -group "${DN_PROJECT_GID}" | wc -l)
    if [[ ${incorrect_files} -gt 0 ]]; then
        n2st::print_msg_error "${DN_PROJECT_PATH} failed ownership test!"
        echo "Found ${incorrect_files} files with incorrect ownership in ${DN_PROJECT_PATH}"
        find ${DN_PROJECT_PATH} ! -user "${DN_PROJECT_UID}" -o ! -group "${DN_PROJECT_GID}" -ls
        exit 1
    else
      n2st::print_msg_done "All files in ${DN_PROJECT_PATH} have correct ownership (${DN_PROJECT_UID}:${DN_PROJECT_GID})"
    fi

    # ....Buildtime debug..........................................................................
    #DN_SHOW_DEBUG_INFO=true
    source /dna-lib-container-tools/dn_sanity_checks.bash && dna::user_and_dir_content_sanity_check "buildtime"
EOF

SHELL ["/bin/bash", "-c"]
ENTRYPOINT [ "/dockerized-norlab/project/project-slurm/dn_entrypoint.slurm.bash" ]
CMD [ "-c","print('>>>Hello-slurm')" ]

