
ARG BASE_IMAGE
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE:?err}:${BASE_IMAGE_TAG:?err} AS norlab-slurm-setup

ARG IS_TEAMCITY_RUN
ENV IS_TEAMCITY_RUN=${IS_TEAMCITY_RUN:-false}

ENV DN_PROJECT_SERVICE=project-slurm
ENV DN_PROJECT_SERVICE_DIR=/dockerized-norlab/project/${DN_PROJECT_SERVICE}


SHELL ["/usr/local/bin/bash-dn-buildtime", "-c"]
ARG DEBIAN_FRONTEND=noninteractive

RUN <<EOF
    echo "Pre-condition checks"
    {
        test $(whoami) == "root" &&  \
        test -n ${DN_PROJECT_USER:?'Env variable need to be set and non-empty.'} && \
        test -d /home/${DN_PROJECT_USER} && \
        test -n ${DN_PROJECT_GIT_NAME:?'Env variable need to be set and non-empty.'} && \
        test -n ${DN_PROJECT_GIT_DOMAIN:?'Env variable need to be set and non-empty.'} ;
    } || exit 1

EOF

WORKDIR /tmp/numba_cache
ENV NUMBA_CACHE_DIR=/tmp/numba_cache

WORKDIR ${DN_PROJECT_SERVICE_DIR}
COPY --chown="$(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER})" --from=context-dna-lib-container-tools project_entrypoints/${DN_PROJECT_SERVICE}/dn_entrypoint.slurm.bash ./
COPY --chown="$(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER})" .dockerized_norlab/configuration/project_entrypoints/project-slurm .

RUN <<EOF
    chmod 777 /tmp/numba_cache

    if [[ -f "/etc/matplotlibrc" ]]; then
        if grep -q 'backend : Agg' "/etc/matplotlibrc" 2>/dev/null; then
            echo "Configure Matplotlib to use a non-interactive backends for TeamCity run"
            echo "backend : Agg" >> /etc/matplotlibrc
        fi
    fi

    chmod +x ./dn_entrypoint.slurm.bash
EOF


# ====Execute slurm run============================================================================
FROM norlab-slurm-setup AS execute-slurm-run

USER ${DN_PROJECT_USER:?err}
SHELL ["/bin/bash", "-c"]
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR ${DN_PROJECT_PATH:?'Required DN environment variable is empty or not set'}
RUN test -x ${DN_PROJECT_SERVICE_DIR}/dn_entrypoint.slurm.bash || exit 1

RUN <<EOF
    # ....Buildtime debug................................................................................
    MSG_WARNING_FORMAT="\033[1;33m"
    MSG_END_FORMAT="\033[0m"
    echo -e "${MSG_WARNING_FORMAT}[DN runtime debug]${MSG_END_FORMAT} Check container DN env var..."
    echo
    printenv | grep -e DN_ -e DNA_ -e PATH -e PYTHONPATH
    echo
    echo -e "${MSG_WARNING_FORMAT}[DN runtime debug]${MSG_END_FORMAT} Check container available files..."
    echo
    tree -aguL 3 /dna-lib-container-tools
    echo
    tree -aguL 3 /project_entrypoints
    echo
    tree -aguL 1  -I .git /
    echo
    tree -aguL 1  -I .git "${DN_PATH}"
    echo
    tree -aguL 1  -I .git "$HOME"
    echo
    tree -aguL 3 -I .git -I utilities /dockerized-norlab/
    echo
    echo -e "${MSG_WARNING_FORMAT}[DN runtime debug]${MSG_END_FORMAT} Users configuration sanity check..."
    echo
    echo "whoami: $(whoami)"
    echo "id ${DN_PROJECT_USER}: $(id "${DN_PROJECT_USER}")"
    echo "DN_CONTAINER_TOOLS_LOADED: ${DN_CONTAINER_TOOLS_LOADED}"
    echo "DEBIAN_FRONTEND: ${DEBIAN_FRONTEND}"
    echo
    echo -e "${MSG_WARNING_FORMAT}[DN runtime debug]${MSG_END_FORMAT} Check users setup..."
    echo "getent passwd root: $(getent passwd root)"
    echo "getent passwd ${DN_SSH_SERVER_USER}: $(getent passwd "${DN_SSH_SERVER_USER}")"
    echo
EOF

ENTRYPOINT [ "/dockerized-norlab/project/project-slurm/dn_entrypoint.slurm.bash" ]
CMD [ "-c","print('>>>Hello-slurm')" ]

